#
# This file contains configuration flags to customize your site
#

bride: Beth
groom : Joe

navlinks:
    - text: The Big Day
      url: /#wedding
    - text: How We Met
      url: /
    - text: The Proposal
      url: /
    - text: The Bridal Party
      url: /
    - text: Accommodations
      url: /
    - text: What's Nearby
      url: /

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-67591322-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://joeandbeth2017.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

# GitHub only supports this flavor of markdown
# that type of highlighter

markdown: kramdown
highlighter: rouge


permalink: /:title/

paginate: 3
paginate_path: "/page:num"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
