# This file contains configuration flags to customize your site

bride: 
    first: Beth
    last: Wirick
    
groom :
    first: Joe
    last: Hendrix
    
date: 2017-08-12

place:
    name: St Christopher
    city: Vandalia
    state: Ohio

colors:
    - "#A6B175"
    - "#C2A4BF"

font: Dancing Script
# Cinzel Decorative

# Various app ids
google_analytics: UA-67591322-1
google_api_key: AIzaSyDEW_nAbT0mgB_r3f7dguJ5-c6vb2sZAgE
fb_app_id: 1660279814248162

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.joeandbeth2017.com

# GitHub only supports "kramdown" flavor of markdown
# and "rouge" type of highlighter

markdown: kramdown
highlighter: rouge

permalink: /:title/
paginate: 3
paginate_path: "/page:num"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
