# This file contains configuration flags to customize your site

bride: Beth
groom : Joe
date: August 12, 2017

colors:
    - "#A6B175"
    - "#C2A4BF"

font: Rouge Script
# Cinzel Decorative

# Various app ids
google_analytics: UA-67591322-1
google_api_key: AIzaSyDEW_nAbT0mgB_r3f7dguJ5-c6vb2sZAgE
fb_app_id: 1660279814248162

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://joeandbeth2017.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# GitHub only supports "kramdown" flavor of markdown
# and "rouge" type of highlighter

markdown: kramdown
highlighter: rouge

permalink: /:title/
paginate: 3
paginate_path: "/page:num"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME